#!/bin/bash
# hipmsg - send messages to hipchat room
#
# original by powdahound: http://github.com/hipchat/hipchat-cli


CURL=`which curl`
PERL=`which perl`

if ! [ -x "$CURL" ]; then
    echo "ERR: curl not found"
    exit 1
fi

if ! [ -x "$PERL" ]; then
    echo "ERR: perl not found"
    exit 1
fi

usage() {
    cat << EOF
    Usage: $0 -t <token> -r <room id> -f <from name>

    This script will send a message to the given room as
    a system message. If -m is not specified it will read from STDIN.

    REQUIRED OPTIONS:
    -t <TOKEN>      API token
    -r <ROOM_ID>    Room ID
    -f <FROM>       From name

    OPTIONS
    -h              Show this message
    -n              Trigger notification for people in the room
    -l              Instead of posting a message, give a list of rooms
    -m <MESSAGE>    Message string to post, overrides <stdin>
    -o <HOST>       API host, defaults to api.hipchat.com
    -c <COLOR>      Message color (yellow, red, green, purple or random - default: yellow)

    ENV VARIABLES
    HIPCHAT_API_TOKEN   Will be used instead of -t if set

EOF
}

TOKEN=
ROOM_ID=
FROM=
COLOR=
MESSAGE=
NOTIFY=0
HOST='api.hipchat.com'

while getopts “hlt:r:f:m:c:o:n” OPTION; do
    case $OPTION in
        h) usage; exit 1;;
        l) LISTROOM=yes;;
        t) TOKEN=$OPTARG;;
        r) ROOM_ID=$OPTARG;;
        f) FROM=$OPTARG;;
        c) COLOR=$OPTARG;;
        m) MESSAGE=$OPTARG;;
        n) NOTIFY=1;;
        o) HOST=$OPTARG;;
        [?]) usage; exit;;
    esac
done

# load env token if present
[ -n "$HIPCHAT_API_TOKEN" ] && TOKEN=$HIPCHAT_API_TOKEN

# check for required args
if [[ -z $TOKEN ]] || [[ -z $ROOM_ID ]] || [[ -z $FROM ]]; then
    echo "ERR: specify a valid token, room_id and from name"
    usage
    exit 1
fi

# always override cmd line if unset chck stdin
if [[ -z $LISTROOM ]] && [[ -z $MESSAGE ]]; then
    if ! [ -t "0" ]; then
        MESSAGE=$(cat)
    else
        echo "ERR: no MESSAGE sepcified"
        exit 1
    fi
fi

# replace newlines with XHTML <br>
MESSAGE=$(echo -n "${MESSAGE}" | sed "s/$/\<br\>/")

# replace bare URLs with real hyperlinks
MESSAGE=$(echo -n "${MESSAGE}" | perl -p -e "s/(?<!href=\")((?:https?|ftp|mailto)\:\/\/[^ \n]*)/\<a href=\"\1\"\>\1\<\/a>/g")

# urlencode with perl
MESSAGE=$(echo -n "${MESSAGE}" | perl -p -e 's/([^A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg')

# do the curl
if [[ -z $LISTROOM ]]; then
    curl -ksS \
    -d "auth_token=$TOKEN&room_id=$ROOM_ID&from=$FROM&color=$COLOR&message=$MESSAGE&notify=$NOTIFY" \
    https://$HOST/v1/rooms/message
else
    echo 'Listing Rooms:'
    result=`curl -skSg "https://$HOST/v1/rooms/list?format=json&auth_token=$TOKEN" 2>&1`
    cat << EOF
    echo $result
EOF
fi
